name: release new version

on:
  push: 
    tags: ['*']

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the source code
        uses: actions/checkout@v3

      - uses: wistia/parse-tool-versions@v1.0

      - uses: earthly/actions-setup@v1
        with: { version: "v${{ env.EARTHLY_TOOL_VERSION }}" }

      - name: Extract tag name
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          earthly \
            --push \
            +build-image \
            --fusionauth_app_version=${{ env.RELEASE_VERSION }} \
            --image_name=ghcr.io/${{ github.repository_owner }}/fusionauth-app-mysql \
            --token ${{ secrets.GITHUB_TOKEN }}
